### PR TITLE
Phase one EDA James 

### PR DESCRIPTION
**Pull request by khonje-ja**
Initial submission

### CODE REVIEW

**Review by teemoo-zz — CHANGES_REQUESTED** [review]
Hi James, I think you have accidentally the **checkpoint file**. Please make a PR with the actual notebook. Thank you.

**Comment by khonje-ja** [comment]
Second submission - Hope this PR works

**Comment by khonje-ja** [comment]
Second submission

**Comment by teemoo-zz** [comment]
Hey James, your second PR still seems to have only the checkpoint file. Let's talk about it in our meeting and see if we can find a fix.

**Pull request closed without merging**
